name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make dependencies

    - name: Build dictionaries
      run: make

    - name: Test dictionaries
      run: make check

    - name: Cache
      uses: actions/cache@v4.0.2
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: 
        # An explicit key for restoring and saving the cache
        key:
